### ISSUE TITLE
Cosmetic - Alignement text

### ISSUE THREAD

**Issue by bengrol** [Shuunen/green-app#169]
Ecran choix des formules. le text "Select" sort de l'écran. 
Voir pour le mettre à la ligne. Si trop long, supprimer ce button.

**Comment by Shuunen** [comment]
![image](https://user-images.githubusercontent.com/439158/77573529-16534e80-6ed1-11ea-9491-aeaba3f6dc97.png)

voilà le rendu sur android, je classe ça bug-ios

**Comment by bengrol** [comment]
![IMG_4D5CEACDD1F1-1](https://user-images.githubusercontent.com/3702150/77641608-9b377a00-6f5c-11ea-991d-d0c48197fcc0.jpeg)

**Comment by bengrol** [comment]
![liste - copie](https://user-images.githubusercontent.com/3702150/77642204-94f5cd80-6f5d-11ea-87e0-7643eab79d9e.jpg)
