### ISSUE TITLE
màj des infos user : route et verbe

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/green-app#181]
un PATCH /me ou PUT /me est manquant pour faire cette manip

**Comment by Shuunen** [comment]
le PUT étant un peu violent pour mettre à jour des données il vaudrait mieux privilégier un PATCH selon moi

la route /me n'est peut-être pas la plus adaptée

je vois que sur /users il faut PUT pour mettre à jour les données utilisateur
est-ce un vrai PUT ? si je n'envoie pas toutes les données de l'utilisateur les données manquantes seront perdues ?

le mieux serait un PATCH /users/:id de mon point de vue

**Comment by neimheadh** [comment]
Sur cette version de Api platform, il faut voir le PUT comme un PATCH.

Un PUT /users/:id ne modifiera que les données transmises

**Comment by neimheadh** [comment]
Pour la route /me, elle tape sur plusieurs entités. C'est faisable de faire un PUT dessus, mais c'est à implémenter totalement.

**Comment by neimheadh** [comment]
PI: Sur la dernière version d'api platform en Symfony 5 le PATCH est présent par défaut, mais l'ancien système peu être gardé si on veut

**Comment by Shuunen** [comment]
c'est pour ça que j'ai demandé si c'était un vrai PUT car je trouvais ça chelou

moi peu importe du moment que j'ai un PATCH (en passant par un faux PUT ou un vrai PATCH)

côté front je ferai une méthode qui s'appellera "patch" mais fera un put pour faire le trick avec cette version d'api platform
