### ISSUE TITLE
màj des infos user : data

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/green-app#201]
Depuis l'app l'user peut modifier nom / prénom / régimes / intolérances / magasin favori / langue d'affichage

il manque ces champs sur la ressource user : 

- allergens (tableau d'allergènes)
- diets (tableau de régimes)
- firstName (string)
- lastName (string)
- locale (string avec la langue sur 2 caractères 'fr', 'en', ...)

**Comment by neimheadh** [comment]
Ok. Todo

**Comment by neimheadh** [comment]
Déployé sur develop

**Comment by Shuunen** [comment]
je fais un get /me : 

```json
{
    "store": null,
    "id": 9,    
    "username": "user5@example.com",
    "email": "user5@example.com",
    "firstname": null,
    "lastname": null,
   "...":"...",
}
```

puis un PUT `/users/9` avec ce body : 

```json
{
    "firstname": "Yves",
    "lastname": "Égée"
}
```

et j'ai : 

```json
{
    "error": "access_denied",
    "error_description": "Access Denied."
}
```

**Comment by Shuunen** [comment]
@neimheadh merci pour le fix, ça fonctionne désormais

**Comment by Shuunen** [comment]
j'arrive à poster : 

```json
{
    "allergens": [],
    "diets": [
        "vegan"
    ],
    "firstname": "John",
    "lastname": "Sacramoni",
    "locale": "en",
    "store": "/stores/2"
}
```

Mais le format des allegens (tableau d'URI) diffère des diets (tableau de string), sur quoi on normalize @neimheadh ?

**Comment by neimheadh** [comment]
Diets est d'un type "array", derrière c'est un champs texte sérialisé. Allergens y'as une entitée derrière. Faut voir si c'est nécessaire de mettre une entité derrière diet, mais je ne pense pas.

**Comment by Shuunen** [comment]
Je ne comprend pas qu'on gère ces deux choses d'une manière différente ?

Des aliments vont contenir tel ou tel allergène, et des aliments seront ou non compatible avec tel ou tel régime... qu'est ce qui justifie d'avoir une entité pour allergens et pas pour diet ?

@bengrol ?

**Comment by bengrol** [comment]
rien ne le justifie. Diet devrait être une entité. Je pense qu'on a dû le rajouter en cours de route suite à un oublie (de ma part)

**Comment by bengrol** [comment]
Après vérifications, on a pas encore géré les Diets dans le back. Il me semble qu'on avait évoqué l'idée de le faire lors d'une évolution ( @Shuunen )
Car il va falloir tagguer chaque produit comme étant 'casher' ou autre et faire matcher avec les 'Diets' des clients.

**Comment by Shuunen** [comment]
ok du coup qu'est ce qu'on fait pour la v1 ? on cache diet sur l'app ?

**Comment by bengrol** [comment]
Oui si tu peux, ou si c'est relou tu mets un message qui dit que les régimes spéciaux seront gérés dans la prochaine version

**Comment by Shuunen** [comment]
fixed in #217
