### ISSUE TITLE
accès à l'admin

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/green-app#202]
En utilisant le couple user / pass habituel j'ai ceci 

![image](https://user-images.githubusercontent.com/439158/79899640-5bee3300-840d-11ea-9f10-cfa545715f64.png)

de même avec le compte "admin"

**Comment by neimheadh** [comment]
Pour rappel: l'authentification a été changé pour utiliser les mails. C'est valable sur l'api et sur l'administration. 

La bonne authentification : superadmin@example.com:superadmin

**Comment by neimheadh** [comment]
Je te laisse la fermer Romain 😊

**Comment by Shuunen** [comment]
> Pour rappel: l'authentification a été changé pour utiliser les mails. C'est valable sur l'api et sur l'administration.
> 
> La bonne authentification : [superadmin@example.com](mailto:superadmin@example.com):superadmin

ahhh make sense now
