### ISSUE TITLE
store "menu" typo

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/green-app#203]
voici un store : 

```json
{
  "@id": "/stores/1",
  "@type": "Store",
  "id": 1,
  "name": "Default store",
  "address": null,
  "phone": null,
  "menu": [
      "/menu_models/5",
      "/menu_models/4",
      "/menu_models/3",
      "/menu_models/2",
      "/menu_models/1"
  ],
  "locale": "/locales/2",
  "currency": "/currencies/2"
}
```

la clé contenant les menus est au singulier, je fais du remapping côté front en attendant ce fix

**Comment by neimheadh** [comment]
Tu préfères que je fasses une version avec les deux typos ou tu es près pour que je vire l'ancienne version direct ?

**Comment by Shuunen** [comment]
quelles deux typos ?

il faut juste que "menu" s'appelle "menus"

**Comment by neimheadh** [comment]
Done, livré sur develop

**Comment by Shuunen** [comment]
vu ! merci
