### ISSUE TITLE
utilisation de "families"

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/green-app#218]
Si un pick c'est : 

```json
{
            "@id": "/menu_picks/1",
            "@type": "MenuPick",
            "amount": 1,
            "families": [
                {
                    "@id": "/families/1",
                    "@type": "Family",
                    "label": "base"
                }
            ]
        }
```

Quel est l'utilité de families ?

S'il y en a plusieurs c'est pour piocher un parmi cette liste ?

@bengrol disait à propos de families "Un truc a virer je pense."

**Comment by bengrol** [comment]
Oui j'ai compris à quoi ça sert. Il faut le garder.

**Comment by Shuunen** [comment]
on peut voir le json de ces deux exemples ?

**Comment by bengrol** [comment]
Pour le 1er, on aurait quelque chose qui ressemble à ça : 
`{
            "@id": "/menu_picks/1",
            "@type": "MenuPick",
            "amount": 1,
            "families": [
                {
                    "@id": "/families/2",
                    "@type": "Family",
                    "label": "entree"
                }
            ]
        },{
            "@id": "/menu_picks/1",
            "@type": "MenuPick",
            "amount": 1,
            "families": [
                {
                    "@id": "/families/1",
                    "@type": "Family",
                    "label": "plat"
                }
            ]
        }`


Pour le 2em : 
`{
            "@id": "/menu_picks/1",
            "@type": "MenuPick",
            "amount": 1,
            "families": [
                {
                    "@id": "/families/1",
                    "@type": "Family",
                    "label": "plat"
                }
            ]
        },{
            "@id": "/menu_picks/1",
            "@type": "MenuPick",
            "amount": 1,
            "families": [
                {
                    "@id": "/families/2",
                    "@type": "Family",
                    "label": "entre"
                },
                {
                    "@id": "/families/3",
                    "@type": "Family",
                    "label": "dessert"
                }
            ]
        }`


J'ai volontairement pris un cas ou il n'y a pas de salade à composer pour pas me faire chier avec tous le détails (base + ingrédients X3 + sauce )

**Comment by Shuunen** [comment]
ok je vois mieux merci
