### ISSUE TITLE
Page post login

### ISSUE THREAD

**Issue by bengrol** [Shuunen/green-app#219]
Créer une page post login contenant simplement le logo, un message d’accueil et 2 gros boutons qu’on peut pas rater. 

![image](https://user-images.githubusercontent.com/3702150/81003762-a929c600-8e4b-11ea-82b8-36c4f9fb9b8a.jpg)

**Comment by bengrol** [comment]
J’ai oublié les drapeaux en bas de la page aussi

**Comment by Shuunen** [comment]
ok je vois

**Comment by Shuunen** [comment]
mais du coup à quoi ressemble le login ?

**Comment by bengrol** [comment]
oui la page login ne bouge pratiquement pas. Il faut juste supprimer le bouton switch qui permet de créer un compte quand on n’en a pas. 
Une possible évolution serait qu’en cas de création de compte l’utilisateur soit dirigé vers un tunnel en trois étapes identique à ce qu’il y a actuellement dans la section « mon compte »

**Comment by Shuunen** [comment]
ok je vais essayer de brancher ça : 

- login > sign in > home
- login > sign up > account edition > home
