### ISSUE TITLE
Supprimer bouton retour à l’accueil

### ISSUE THREAD

**Issue by bengrol** [Shuunen/green-app#230]
Page Mon compte : 

- supprimer lien "retour" (double emploi)

- remplacer "se déconnecter" par un picto 'log out" en haut à DROITE

ex : 
![152535](https://user-images.githubusercontent.com/3702150/81504984-b4b63a80-92ec-11ea-91c1-58608bf171d1.png)

![screenshot_01](https://user-images.githubusercontent.com/3702150/81504914-4ffae000-92ec-11ea-8a24-c8940d6c8e14.jpg)

**Comment by Shuunen** [comment]
Du coup 
1. en haut à gauche à la place de l'icône home une icône logout pour se déconnecter
2. Suppression du bouton de déconnexion actuel 

 ? 

Sinon il y a un paquet de soucis d'affichage sur iOS à ce que je vois...

**Comment by bengrol** [comment]
c'est comment sur Android ?

**Comment by bengrol** [comment]
En haut à droite plutot le logout. Comme ça on laisse le Home

**Comment by Shuunen** [comment]
sur android : 

![image](https://user-images.githubusercontent.com/439158/81505657-2db79100-92f1-11ea-9a41-39c5c5a1c066.png)

**Comment by Shuunen** [comment]
voilà ce que ça donne, tu valides ?

![image](https://user-images.githubusercontent.com/439158/81505742-de259500-92f1-11ea-9890-22ba7e196cba.png)

**Comment by bengrol** [comment]
Oui c'est bien comme ça.
En passant, si tu peux ajouter des classes sur les textes également, car j'ai l'impression que par default les textes sont tous blancs. Du coup on ne les voit pas.

**Comment by Shuunen** [comment]
des classes css ?

**Comment by Shuunen** [comment]
ça par exemple c'est le bloc responsable de l'affichage des allergènes : 

```html
 <StackLayout v-if="user.allergens && user.allergens.length">
              <Label class="mt-l fz-s uppercase" :text="$t('account.my-allergens')" />
              <Label class="bold alt fz-m" :text="readableList(allergens, user.allergens)" />
 </StackLayout>
```

et y'a des classes pour styliser le rendu sur les deux textes

**Comment by bengrol** [comment]
Je pense que si tu ajoute la classe black, ça fait le job.

``` 
<StackLayout v-if="user.allergens && user.allergens.length">
              <Label class="mt-l fz-s uppercase black" :text="$t('account.my-allergens')" />
              <Label class="bold alt fz-m" :text="readableList(allergens, user.allergens)" />
 </StackLayout>
```

**Comment by bengrol** [comment]
https://github.com/Shuunen/green-app/blob/f6e61d741ba7b2bb93b7322823c83bfe6106492f/app/pages/login.vue#L7

**Comment by Shuunen** [comment]
j'ai compris avec un peu de contexte 😄

**Comment by bengrol** [comment]
je viens de découvrir qu'on peut référencer un morceau de code dans un commentaire d'issue.
