### ISSUE TITLE
page de selection des articles

### ISSUE THREAD

**Issue by bengrol** [Shuunen/green-app#231]
Remplacer le texte « Commander cette formule » Par « Ajouter au panier »

**Comment by Shuunen** [comment]
et on affiche plus le prix du coup ?

**Comment by Shuunen** [comment]
![image](https://user-images.githubusercontent.com/439158/81505987-a61f5180-92f3-11ea-9fb3-7c84713beff5.png)

**Comment by bengrol** [comment]
non

**Comment by Shuunen** [comment]
![image](https://user-images.githubusercontent.com/439158/81506190-e6330400-92f4-11ea-8043-bc83b830b637.png)

gut ?

**Comment by bengrol** [comment]
oui

**Comment by bengrol** [comment]
Je n'ai pas ce texte sur IOS


![Capture d’écran 2020-05-10 à 19 36 07](https://user-images.githubusercontent.com/3702150/81506289-8d17a000-92f5-11ea-82d7-5eef36474035.png)

**Comment by Shuunen** [comment]
> Je n'ai pas ce texte sur IOS

je met une classe `black` dessus du coup
