### ISSUE TITLE
penser au casse couille 

### ISSUE THREAD

**Issue by bengrol** [Shuunen/green-app#235]
Il faut ajouter l'option "pas de sauce".
A voir ce qui est le mieux. ou bien créer en back une item " pas de sauce" mais il faudrait qu'il hérite d'un produit model "lambda".
Ou alors le gérer dans le front.

@Shuunen @neimheadh j'attends vos remarques

**Comment by Shuunen** [comment]
De mon point de vue c'est un item comme un autre, sur la commande il y aura bien une ligne "pas de sauce", du coup c'est pas le genre de truc qu'un front gère selon moi.

**Comment by bengrol** [comment]
OK

**Comment by Shuunen** [comment]
à voir avec @neimheadh

**Comment by Shuunen** [comment]
@bengrol v1 ou v2 ?

**Comment by bengrol** [comment]
A faire dans le back
