### ISSUE TITLE
Ordre des picks 

### ISSUE THREAD

**Issue by bengrol** [Shuunen/green-app#242]
Pour que l'utilisateur choisisse les picks de sa formule dans l'ordre logique ( entré - plats - salade - etc.. ) le plus simple/efficace serait-il de mettre un ordre d'affichage sur le pick ou sur la famille ?

Selon ce que je sais du back, le plus simple serait sur la famille, mais à voir avec le front.

**Comment by Shuunen** [comment]
pourquoi ne pas simplement ordonner le tableau renvoyé par le back ?

**Comment by bengrol** [comment]
l'ordonner par rapport à quoi ?

**Comment by bengrol** [comment]
Tu veux dire directement dans l'API ? C'est jouable effectivement, mais il nous faut quand même nous baser qq chose pour l'ordonner.

**Comment by Shuunen** [comment]
> l'ordonner par rapport à quoi ?

plutôt que de renvoyer un tableau [4, 1, 5, 3, 2] , renvoyer un tableau ordonné [ 1, 2, 3, 4, 5] et le front l'affichera dans le même ordre, ça évite d'implémenter de la logique d'affichage en plus.

après oui à voir comment côté back vous voulez faire ça

**Comment by bengrol** [comment]
Closed via #249
