### ISSUE TITLE
Changement Mail

### ISSUE THREAD

**Issue by bengrol** [Shuunen/green-app#248]
On à définit le Username comme étant le mail du client.
Que se passe-t-il quand il change de mail ?
Est-ce qu'il ne faudrait pas (dans une V2/3) lui générer un username avec nom+prenom+lettre aléatoire. Quelque chose de fixe

**Comment by bengrol** [comment]
Vu avec @Shuunen - Le username est a generer par le back avec les nom+Prenom+Chiffre Random. 
Voir si il est possible de se connecter soit avec son mail soit avec le username.

**Comment by Shuunen** [comment]
lors de la création d'un compte je fais actuellement un POST sur `/users` :

```json
{ "email": "romain.racamier@gmoule.com", "username": "romain.racamier@gmoule.com", "plainPassword": "superPass123"}
```

**Comment by bengrol** [comment]
#264

**Comment by bengrol** [comment]
vu avec @neimheadh - le changement d'email change également le username. Donc en cas de changement de mail, il sera possible se connecter avec le nouveau.
Ce qui veut dire qu'on abandonne l'histoire de user name et les US qui s'y rapportent

**Comment by Shuunen** [comment]
Ok faudra qu'on pense à clôturer les issues liées
