### ISSUE TITLE
bouton retour inactif

### ISSUE THREAD

**Issue by bengrol** [Shuunen/green-app#294]
Le bouton retour sur la page mon compte est inactif. Il n'y a rien du tout dans les logs comme si il n'existait pas ou n'était pas cliquable.
Le log devrait au moins afficher : 
` console.log('account edit : user canceled')`

![Capture d’écran 2020-06-23 à 13 17 17](https://user-images.githubusercontent.com/3702150/85397484-e2c9a400-b553-11ea-8961-1d70a8eb97d0.png)

**Comment by bengrol** [comment]
Précisions : il n'est pas inactif quand on arrive sur la page. Il l'est quand on mets à jour les infos et qu'on a enregistré

**Comment by Shuunen** [comment]
je n'arrive pas à le reproduire, que ce soit en arrivant sur la page; ou après avoir remplis tous les champs, le retour sur la page mon compte se fait, j'ai bien le log `JS: account edit : user canceled`

2 hypothèses : 
1) c'est un pb sur iOS uniquement
2) le pb était dû à autre chose et cela a été corrigé

**Comment by bengrol** [comment]
Ce bug a été corrigé ( je sais pas comment )
