### ISSUE TITLE
Refacto /m/pay

### ISSUE THREAD

**Issue by Shuunen** [Shuunen/green-app#299]
Changer la route et définir le payload minimal

**Comment by bengrol** [comment]
Voici un payload pour une commande composée de 2 menus. 

`id_menu_model` est assez explicite je pense. 
`products` est un tableau d'id de Product. 

```
{
   "menus":[
      {
         "id_menu_model":2,
         "products":[
            2,
            4,
            5,
            6,
            8
         ]
      },
      {
         "id_menu_model":4,
         "products":[
            4,
            5,
            7
         ]
      }
   ]
}
```

**Comment by Shuunen** [comment]
LE PAYLOAD 🤣

**Comment by bengrol** [comment]
Par contre je pense à une chose. En cas d'extra, il faut que le client soit au courant de l'article qui lui est facturé en +
Tu pourrais m'envoyer l'info sous cette forme ?

```
{
   "menus":[
      {
         "id_menu_model":2,
         "products":[
            2,
            4,
            5,
            6,
            8
         ],
        "extra":[
           2,
           5
        ]
      }
   ]
}
```

**Comment by Shuunen** [comment]
Yes pas de soucis, avec un "s" à extra par convention pour les listes
